import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
// Generated by @tanstack/router-plugin from src/routes/** on every dev/build run
// (vite.config.ts). Never hand-edited, and not committed — see .gitignore.
import { routeTree } from './routeTree.gen'

// Scaffold only (T003): a query client with library defaults and a router with no
// session bootstrap. T017 replaces this with the real shell — `GET /api/me`, the API
// client that branches on the error `code`, and the footer (T098a).
const queryClient = new QueryClient()
const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('Root element #root not found')
}

createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
