import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
// Generated by @tanstack/router-plugin from src/routes/** on every dev/build run
// (vite.config.ts). Never hand-edited, and not committed — see .gitignore.
import { routeTree } from './routeTree.gen'

// The web shell (T017): one query client, shared with the router so the root route's
// `beforeLoad` can bootstrap the session through `GET /api/me` (see routes/__root.tsx) via
// `queryClient.ensureQueryData` instead of a second, disconnected fetch.
const queryClient = new QueryClient()
const router = createRouter({
  routeTree,
  context: { queryClient },
  // Router-level defaults; __root.tsx's `pendingComponent` is what a slow `beforeLoad` shows.
  defaultPreload: 'intent',
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('Root element #root not found')
}

createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
